ALTER TABLE prod_serial_enttlmnt DROP COLUMN tenant_id ;     
ALTER TABLE prod_serial_enttlmnt DROP COLUMN status ;        
ALTER TABLE prod_serial_enttlmnt DROP COLUMN source ;        
ALTER TABLE prod_serial_enttlmnt DROP COLUMN audit_status;
ALTER TABLE prod_serial_enttlmnt DROP COLUMN prod_regn_id  ; 
ALTER TABLE prod_serial_enttlmnt DROP COLUMN plcy_id ;       
ALTER TABLE prod_serial_enttlmnt DROP COLUMN plcy_type ;     
ALTER TABLE prod_serial_enttlmnt DROP COLUMN plcy_code ;     
ALTER TABLE prod_serial_enttlmnt DROP COLUMN plcy_name  ;    
ALTER TABLE prod_serial_enttlmnt DROP COLUMN plcy_description;
ALTER TABLE prod_serial_enttlmnt DROP COLUMN term_id  ;      
ALTER TABLE prod_serial_enttlmnt DROP COLUMN term_type    ;  
ALTER TABLE prod_serial_enttlmnt DROP COLUMN term_code ;     
ALTER TABLE prod_serial_enttlmnt DROP COLUMN term_name   ;   
ALTER TABLE prod_serial_enttlmnt DROP COLUMN term_description;
ALTER TABLE prod_serial_enttlmnt DROP COLUMN start_date  ;   
ALTER TABLE prod_serial_enttlmnt DROP COLUMN end_date   ;    
ALTER TABLE prod_serial_enttlmnt DROP COLUMN duration  ;     
ALTER TABLE prod_serial_enttlmnt DROP COLUMN duration_uom   ;
ALTER TABLE prod_serial_enttlmnt DROP COLUMN usg_uom1 ;      
ALTER TABLE prod_serial_enttlmnt DROP COLUMN usg_from_val1  ;
ALTER TABLE prod_serial_enttlmnt DROP COLUMN usg_to_val1   ; 
ALTER TABLE prod_serial_enttlmnt DROP COLUMN usg_uom2;       
ALTER TABLE prod_serial_enttlmnt DROP COLUMN usg_from_val2  ;
ALTER TABLE prod_serial_enttlmnt DROP COLUMN usg_to_val2 ;   
ALTER TABLE prod_serial_enttlmnt DROP COLUMN usg_uom3  ;     
ALTER TABLE prod_serial_enttlmnt DROP COLUMN usg_from_val3 ; 
ALTER TABLE prod_serial_enttlmnt DROP COLUMN usg_to_val3 ;   
ALTER TABLE prod_serial_enttlmnt DROP COLUMN created_date   ;
ALTER TABLE prod_serial_enttlmnt DROP COLUMN updated_date ;  
ALTER TABLE prod_serial_enttlmnt DROP COLUMN created_by;     
ALTER TABLE prod_serial_enttlmnt DROP COLUMN updated_by  ;   
ALTER TABLE prod_serial_enttlmnt DROP COLUMN created_by_user;
ALTER TABLE prod_serial_enttlmnt DROP COLUMN updated_by_user;
ALTER TABLE prod_serial_enttlmnt DROP COLUMN plan_id  ;      
ALTER TABLE prod_serial_enttlmnt DROP COLUMN plan_code ;    
set foreign_key_checks=0;
ALTER TABLE prod_serial_enttlmnt modify enttlmnt_id bigint(20) NOT NULL;
set foreign_key_checks=1;
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN plcy_id;          
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN plcy_type ;       
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN plcy_code ;       
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN plcy_name ;       
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN plcy_description ;
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN term_id  ;        
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN term_type ;       
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN term_code  ;      
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN term_name  ;      
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN term_description ;
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN start_date;       
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN end_date ;        
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN duration ;        
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN duration_uom ;    
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN usg_uom1 ;        
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN usg_from_val1  ;  
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN usg_to_val1 ;     
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN usg_uom2  ;       
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN usg_from_val2  ;  
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN usg_to_val2  ;    
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN usg_uom3  ;       
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN usg_from_val3    ;
ALTER TABLE srvc_plan_enttlmnt DROP COLUMN usg_to_val3;
set foreign_key_checks=0;
ALTER TABLE srvc_plan_enttlmnt MODIFY enttlmnt_id bigint(20) NOT NULL;
set foreign_key_checks=0;